# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('FL', 'Florida')], max_length=1),
        ),
    ]
