# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20171129_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('FL', 'Florida')], default='FL', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
