# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20171130_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('Bro', 'Brother'), ('Sis', 'Sister')], max_length=3),
        ),
    ]
