# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20171203_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='Tampa', max_length=128),
        ),
    ]
