# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20171203_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.CharField(choices=[('Coor', 'Study Group Coordinator'), ('FOICapt', 'FOI Captain'), ('MGTCapt', 'MGT Captain'), ('Sect', 'Secretary')], default='FL', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Bro', 'Brother'), ('Sis', 'Sister')], max_length=3),
        ),
    ]
