# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20171207_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.CharField(choices=[('Coor', 'Study Group Coordinator'), ('FOICapt', 'FOI Captain'), ('MGTCapt', 'MGT Captain'), ('Sect', 'Secretary')], max_length=7),
        ),
    ]
