# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_phone_number_formated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_formated',
            field=models.CharField(max_length=15, verbose_name='Phone #'),
        ),
    ]
